version: '3'

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:${TAG}"
    volumes:
      - elastic-vol:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:$TAG
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
     - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:${TAG}
    volumes:
      - ${CONFIG}:/usr/share/logstash/config/logstash.yml
      - ${PIPELINES}:/usr/share/logstash/config/pipeline
      - ${LOGS}:/usr/share/logstash/logs
    ports:
      - "5000:5000"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk: 

volumes:
  elastic-vol:
